name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  push:
    branches:
      - main

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: █
          CODE_LANG: rust
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          STOP_AT_OTHER: false
          IGNORED_LANGUAGES: Binary YAML XML JSON Bash Other Text
